source 'https://github.com/CocoaPods/Specs.git'

target 'HYPImagePicker', :exclusive => true do
  pod "HYPImagePicker", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "HYPImagePicker", :path => "../"


end
